### ISSUE TITLE
Hapi v17 Support

### ISSUE THREAD

**Issue by timcosta** [brainsiq/hapi-boom-decorators#51]
### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`, as well as deprecating some other rarely used functionality. This is a breaking change that may make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [x] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [x] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [x] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.
* This issue is being opened because your plugin is listed on the official hapi website

**Comment by brainsiq** [comment]
I will update the plugin

**Comment by brainsiq** [comment]
I have decided for now not to update this module to work with hapi v17. The new API for returning responses seems to make this plugin unnecessary as the example usage below shows:

With hapi v17 and no plugins:

```
server.route({
  method: 'GET',
  path: '/resource/{id}',
  handler: (request, h) => {
    throw boom.notFound();
  }
});
```

With a plugin for decorating the toolkit with boom functions:

```
server.route({
  method: 'GET',
  path: '/resource/{id}',
  handler: (request, h) => {
    return h.notFound();
  }
})
```

There is very little difference in terms of verbosity, which was the main driver for creating this module in the first place. If anyone can convince me otherwise I am open to updating.

**Comment by BigWillie** [comment]
Without the plugin, you have to require boom in all your route files...  `const Boom = require('boom');`
However, with the plugin - you just call it.. `return h.notFound();`

**Comment by brainsiq** [comment]
@BigWillie I'd done most of the work already so I've just gone and published a new version (4.0.0) for hapi 17.
